codestates-seb/seb40_main_012

back/src/main/java/seb40_main_012/back/bookCollection/controller/CollectionController.java, back/src/main/java/seb40_main_012/back/bookCollection/dto/CollectionDto.java, back/src/main/java/seb40_main_012/back/bookCollection/entity/BookCollection.java, back/src/main/java/seb40_main_012/back/bookCollection/repository/CollectionRepository.java, back/src/main/java/seb40_main_012/back/bookCollection/service/CollectionService.java, back/src/main/java/seb40_main_012/back/collectionLike/dto/CollectionLikeDto.java, back/src/main/java/seb40_main_012/back/collectionLike/entity/CollectionLike.java, back/src/main/java/seb40_main_012/back/collectionLike/repository/CollectionLikeRepository.java, back/src/main/java/seb40_main_012/back/collectionTag/dto/CollectionTagDto.java, back/src/main/java/seb40_main_012/back/collectionTag/entity/CollectionTag.java, back/src/main/java/seb40_main_012/back/collectionTag/repository/CollectionTagRepository.java, back/src/main/java/seb40_main_012/back/user/controller/UserController.java, back/src/main/java/seb40_main_012/back/user/dto/UserDto.java, back/src/main/java/seb40_main_012/back/user/entity/User.java, back/src/main/java/seb40_main_012/back/user/repository/UserRepository.java, back/src/main/java/seb40_main_012/back/user/service/UserService.java, back/src/main/java/seb40_main_012/back/userCategory/dto/UserCategoryDto.java, back/src/main/java/seb40_main_012/back/userCategory/entity/Category.java, back/src/main/java/seb40_main_012/back/userCategory/entity/CategoryType.java, back/src/main/java/seb40_main_012/back/userCategory/entity/UserCategory.java, back/src/main/java/seb40_main_012/back/userCategory/repository/UserCategoryRepository.java, back/src/main/java/seb40_main_012/back/userRole/Role.java, back/src/main/java/seb40_main_012/back/userRole/RoleType.java, back/src/main/java/seb40_main_012/back/userRole/UserRole.java
=> chore: user,collection 템플릿 작성

back/src/main/java/seb40_main_012/back/book/BookDto.java, back/src/main/java/seb40_main_012/back/book/entity/Book.java, back/src/main/java/seb40_main_012/back/bookCollectionBook/BookCollectionBookDto.java, back/src/main/java/seb40_main_012/back/bookWiki/BookWiki.java, back/src/main/java/seb40_main_012/back/bookWiki/BookWikiDto.java, back/src/main/java/seb40_main_012/back/common/comment/CommentDto.java, back/src/main/java/seb40_main_012/back/common/comment/CommentMapper.java, back/src/main/java/seb40_main_012/back/common/image/Image.java, back/src/main/java/seb40_main_012/back/pairing/PairingDto.java, back/src/main/java/seb40_main_012/back/pairing/entity/Pairing.java
=> [BE]Fix MapperImpl Error

back/build.gradle
=> [BE]Fear Api Documentation

back/src/main/java/seb40_main_012/back/user/dto/UserCategoryDto.java, back/src/main/java/seb40_main_012/back/user/dto/UserDto.java, back/src/main/java/seb40_main_012/back/user/entity/User.java
=> [BE]Fix Typo

front/src/components/Header.js
별건아니고 디자인 요소만 조금 추가했습니다! 바로 머지하겠습니다
=> [FE] style: Header 메뉴 버튼 디자인 추가

back/src/main/java/seb40_main_012/back/config/auth/dto/LoginDto.java, back/src/main/java/seb40_main_012/back/config/auth/filter/JwtAuthenticationFilter.java, back/src/main/java/seb40_main_012/back/user/controller/UserController.java, back/src/main/java/seb40_main_012/back/user/entity/User.java, back/src/main/java/seb40_main_012/back/user/service/UserService.java
=> [BE] fix: 회원가입, 로그인 수정 사항 반영

front/src/pages/SignUpPage/SignUpPage.js, front/src/pages/SignUpPage/SignUpTextField.js, front/src/store/modules/signUpSlice.js
https://user-images.githubusercontent.com/20276678/202069661-a51e8db0-62c7-4530-ad09-1835867e1679.mov
https://user-images.githubusercontent.com/20276678/202069485-6e5a1013-ef5c-4818-be62-19c52c377cf9.mov
회원가입 유효성 검사 수정했습니다.
닉네임, 회원가입 중복확인 api 개발 후 연동 예정입니다.
=> [FE] feat: 회원가입 유효성 검사 수정

front/src/components/TestComponent/BasicModalTest.js, front/src/components/TestComponent/BasicSelectTest.js, front/src/pages/Temp_Redux.js
Temp_Redux 페이지에 mui 가이드 그대로 복붙했는데 잘 동작합니다.
`node_modules` 폴더, `package-lock.json` 파일 삭제하시고 다시 `npm i` 해보시길 추천드립니다.
=> [FE] test: mui components

front/src/pages/Temp_Redux.js, front/src/styles/theme.js
=> [FE] fix: mui themeprovider error

front/src/App.js, front/src/components/Buttons.js, front/src/pages/TestPage/ButtonTest.js, front/src/pages/TestPage/Temp_Redux.js
=> [FE] style: 버튼 컴포넌트 스타일 추가

front/src/api/duplicationCheckApi.js, front/src/api/requests.js, front/src/store/modules/signUpSlice.js, front/src/util/util.js
- /util/util.js duplicationCheck
=> [FE] 회원가입 닉네임, 이메일 중복확인

front/src/store/modules/authSlice.js
=> [FE] feat: 로그인 후 로그인 유저정보 store

front/src/components/Comments/Comment.js, front/src/components/Comments/CommentAdd.js, front/src/components/Comments/Comments.js, front/src/components/Comments/CommentsHeader.js, front/src/pages/CollectionDetailPage/CollectionDetail.js, front/src/pages/PairingPage/PairingDetail/PairingDetail.js, front/src/store/modules/pairingSlice.js
- 로그인했을 때만 코멘트 등록이 가능합니다.
- 내가 작성한 코멘트만 삭제 및 수정이 가능하도록 기능 추가할 예정입니다!
=> [FE] feat: 페어링 comment 추가, 삭제 기능

front/src/components/Comments/Comment.js, front/src/components/Comments/CommentAdd.js, front/src/components/Comments/Comments.js, front/src/store/modules/authSlice.js
=> [FE] 댓글 부가 기능

back/src/main/java/seb40_main_012/back/config/CorsConfig.java, back/src/main/java/seb40_main_012/back/config/auth/SecurityController.java, back/src/main/java/seb40_main_012/back/config/auth/filter/JwtAuthenticationFilter.java, back/src/main/java/seb40_main_012/back/config/auth/handler/UserLogoutHandler.java, back/src/main/resources/application.yml
- Access Token 만료시간 수정 (30분 -> 2시간)
- response에 Cookie -> Set-Cookie로 변경
- Cookie 유효시간 하루로 변경
=> [BE] fix: Cookie 수정

front/src/pages/MyPage/EditProfile/ChangePassWd.js, front/src/pages/MyPage/EditProfile/ChangePassWdTextFields.js, front/src/pages/MyPage/EditProfile/EditProfileMain.js, front/src/pages/MyPage/EditProfile/PassWdTextFields.js, front/src/pages/MyPage/EditProfile/WithDrawal.js, front/src/store/modules/changePassWdSlice.js, front/src/store/store.js
=> [FE] mypage merge 

back/src/main/generated/seb40_main_012/back/book/BookMapperImpl.java, back/src/main/generated/seb40_main_012/back/common/comment/CommentMapperImpl.java, back/src/main/generated/seb40_main_012/back/follow/FollowMapperImpl.java, back/src/main/generated/seb40_main_012/back/pairing/PairingMapperImpl.java, back/src/main/java/seb40_main_012/back/bookCollection/controller/BookCollectionController.java, back/src/main/java/seb40_main_012/back/bookCollection/dto/BookCollectionDto.java, back/src/main/java/seb40_main_012/back/bookCollection/service/BookCollectionService.java, back/src/main/java/seb40_main_012/back/common/comment/CommentController.java
양귀자 작가의 책을 조회하는 로직입니다.
조회해올 작가와 해당 컬렉션 이름을 수동 변경할 수 있도록 구현했습니다.
=> [BE] Feat: 작가 컬렉션 조회 로직 구현

back/src/main/java/seb40_main_012/back/bookCollection/controller/BookCollectionController.java, back/src/main/java/seb40_main_012/back/bookCollection/dto/BookCollectionDto.java, back/src/main/java/seb40_main_012/back/bookCollection/service/BookCollectionService.java
*해당 컬렉션은 조회 기준이 없기 때문에 db에 있는 컬렉션 3번을 무조건 조회해옵니다.
=> [BE] Feat: 3rd 컬렉션 조회 로직 구현

back/src/main/java/seb40_main_012/back/common/comment/CommentController.java, back/src/main/java/seb40_main_012/back/common/comment/CommentService.java
*기존 태영님 로직에 통합되어 있던 코드를 살렸습니다.
=> [BE] Feat: 컬렉션 코멘트 작성 기능 구현

back/src/main/java/seb40_main_012/back/bookCollection/dto/BookCollectionDto.java, back/src/main/java/seb40_main_012/back/bookCollection/entity/BookCollection.java, back/src/main/java/seb40_main_012/back/bookCollection/service/BookCollectionService.java, back/src/main/java/seb40_main_012/back/common/comment/CommentService.java, back/src/main/java/seb40_main_012/back/stub/Stub.java
컬렉션 테스트를 위한 스텁데이터와 컬렉션 상세에서 코멘트를 조회하는 로직이 추가되었습니다.
=> [BE] Fix: 컬렉션 상세 > 코멘트 조회 추가 & 테스트용 스텁 데이터 추가

back/src/main/java/seb40_main_012/back/common/bookmark/BookmarkService.java
=> [BE] Chore: 커밋에서 빠진 내용 추가

back/src/main/java/seb40_main_012/back/common/comment/CommentDto.java, back/src/main/java/seb40_main_012/back/user/controller/UserController.java, back/src/main/java/seb40_main_012/back/user/service/UserService.java
선례님과 논의 후 컨텐츠 별 response를 분기하도록 처리하였습니다.
=> [BE] Fix: 내 코멘트 조회 분기 처리 로직 추가

back/src/main/java/seb40_main_012/back/book/BookRepository.java, back/src/main/java/seb40_main_012/back/book/BookSpecification.java, back/src/main/java/seb40_main_012/back/bookCollection/controller/BookCollectionController.java, back/src/main/java/seb40_main_012/back/bookCollection/service/BookCollectionService.java, back/src/main/java/seb40_main_012/back/bookCollectionBook/BookCollectionBookRepository.java, back/src/main/java/seb40_main_012/back/user/repository/UserCategoryRepository.java
- api/collections/category2 로 만들었습니다
=> [BE] feat: 사용자 선호 장르로 컬렉션 조회

back/src/main/java/seb40_main_012/back/user/dto/UserInfoDto.java, back/src/main/java/seb40_main_012/back/user/entity/enums/AgeType.java, back/src/main/java/seb40_main_012/back/user/entity/enums/GenderType.java
Enum이 null 값을 저장하지 못하는 문제로 각 타입에 none 타입을 추가하였습니다.
(엔티티 필드에 바로 붙어 분기 처리 또한 불가능)
=> [BE] Fix: UserInfo GenderType/AgeType NONE 타입 추가

back/src/main/generated/seb40_main_012/back/book/BookMapperImpl.java, back/src/main/generated/seb40_main_012/back/bookWiki/BookWikiMapperImpl.java, back/src/main/generated/seb40_main_012/back/common/comment/CommentMapperImpl.java, back/src/main/generated/seb40_main_012/back/follow/FollowMapperImpl.java, back/src/main/generated/seb40_main_012/back/pairing/PairingMapperImpl.java, back/src/main/generated/seb40_main_012/back/user/mapper/UserMapperImpl.java, back/src/main/java/seb40_main_012/back/user/dto/UserInfoDto.java, back/src/main/java/seb40_main_012/back/user/entity/User.java, back/src/main/java/seb40_main_012/back/user/repository/UserCategoryRepository.java, back/src/main/java/seb40_main_012/back/user/service/UserService.java
영속성 문제로 발생했던 NPE 에러를 오랜 삽질 끝에 해결했습니다.
함께 힘써주신 하영님과 태영님께 이 영광을...
=> [BE] Fix: UserInfo 선호 장르 500에러 해결

back/src/main/java/seb40_main_012/back/book/entity/Book.java, back/src/main/java/seb40_main_012/back/common/bookmark/Bookmark.java, back/src/main/java/seb40_main_012/back/pairing/entity/Pairing.java, back/src/main/java/seb40_main_012/back/user/service/UserService.java
연관관계 문제인줄 알고 삽질했던 지난 날들...
어이없게도 호출 로직 문제였습니다. 디버깅 꼼꼼히 살펴보지 않은 것..반성합니다 그리고 죄송합니다
:face_holding_back_tears:
=> [BE] Fix: 북마크 조회 NPE 해결

back/src/main/java/seb40_main_012/back/bookCollection/controller/BookCollectionController.java, back/src/main/java/seb40_main_012/back/bookCollection/dto/BookCollectionDto.java, back/src/main/java/seb40_main_012/back/bookCollection/repository/BookCollectionRepository.java, back/src/main/java/seb40_main_012/back/bookCollection/service/BookCollectionService.java, back/src/main/java/seb40_main_012/back/bookCollectionBook/BookCollectionBookRepository.java, back/src/main/java/seb40_main_012/back/common/bookmark/BookmarkDto.java, back/src/main/java/seb40_main_012/back/common/bookmark/BookmarkRepository.java, back/src/main/java/seb40_main_012/back/common/mypage/MyPageRepositorySupport.java, back/src/main/java/seb40_main_012/back/user/controller/UserController.java, back/src/main/java/seb40_main_012/back/user/service/UserService.java
+ 컬렉션 작성 -> 북마크 책 조회 uri 잘못 작성되어 있던 부분 함께 수정
=> [BE] Fix: 무한스크롤 북마크 조회 아이디 추가(조회 로직 변경)

back/src/main/java/seb40_main_012/back/bookCollection/controller/BookCollectionController.java, back/src/main/java/seb40_main_012/back/bookCollection/repository/BookCollectionRepositorySupport.java, back/src/main/java/seb40_main_012/back/bookCollection/service/BookCollectionService.java
=> [BE] Fix: 인기 컬렉션 limit 변경 및 맞춤 컬렉션 디폴트 케이스 추가

front/src/pages/MyPage/Header.js, front/src/pages/MyPage/MyCollection/Content.js, front/src/pages/MyPage/MyCollection/MyCollectionDetail.js, front/src/pages/MyPage/MyComment/Content.js, front/src/pages/MyPage/MyComment/MyCommentDetail.js, front/src/pages/MyPage/MyComment/NavigateBook.js, front/src/pages/MyPage/MyPairing/Content.js, front/src/pages/MyPage/MyPairing/MyPairingDetail.js, front/src/pages/MyPage/MyPick/MyPickBook.js, front/src/pages/MyPage/MyPick/MyPickCollection.js, front/src/pages/MyPage/MyPick/MyPickPairing.js
* 편의성을 위해 클릭해도 alert나 modal 없이 바로 삭제되게 수정하였습니다
=> [FE] fix: 북마크 삭제 기능 변경

front/src/api/authApi.js, front/src/api/axios.js
Reverts codestates-seb/seb40_main_012#440
=> Revert "[FE] fix: 토큰 local storage 저장으로 수정"

back/src/main/java/seb40_main_012/back/bookCollection/entity/BookCollection.java
컬렉션 클래스에 아래 애너테이션을 붙여 해결하였으나 근본적인 문제 해결을 위해 더 고민해볼 생각입니다..
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
=> [BE] Fix: 책 상세에서의 컬렉션 lazy 로드 문제 해결

front/package-lock.json, front/package.json, front/src/components/RoutesComponent.js, front/src/containers/Header.js, front/src/pages/LandingMobile.js, front/src/pages/LandingPC.js, front/src/pages/LandingPad.js, front/src/pages/LandingPage.js
* 랜딩 페이지 제작했습니다
PC : width 700px 이상
Pad : width 410px 이상 
Mobile : width 410px 미만 (최적 : 아이폰SE 375x667 사이즈)
* 이메일 발송 이미지도 제작했습니다 😊
=> [FE] 랜딩 페이지 제작 
